# Generated by Django 5.2.1 on 2025-05-29 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgencyCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name (English)')),
                ('full_name_bn', models.CharField(blank=True, max_length=200, verbose_name='Full Name (Bangla)')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('Other', 'Other')], default='Other', max_length=10)),
                ('blood_group_other', models.CharField(blank=True, help_text='If Other, specify here', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='cv_pictures/')),
                ('language', models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla'), ('Other', 'Other')], default='English', max_length=20)),
                ('language_other', models.CharField(blank=True, help_text='If Other, specify here', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField(blank=True)),
                ('is_permanent_same_as_current', models.BooleanField(default=False)),
                ('fathers_name', models.CharField(max_length=200)),
                ('fathers_mobile', models.CharField(max_length=20)),
                ('fathers_nid', models.CharField(max_length=20)),
                ('mothers_name', models.CharField(max_length=200)),
                ('mothers_mobile', models.CharField(max_length=20)),
                ('mothers_nid', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('last_education', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('HONOURS', 'Honours'), ('Others', 'Others')], default='SSC', max_length=20)),
                ('last_education_other', models.CharField(blank=True, help_text='If Others, specify here', max_length=100)),
                ('last_education_result', models.CharField(max_length=100)),
                ('last_education_passing_year', models.PositiveIntegerField()),
                ('current_job_status', models.CharField(choices=[('Unemployed', 'Unemployed'), ('Employed', 'Employed'), ('Student', 'Student'), ('Others', 'Others')], default='Unemployed', max_length=20)),
                ('current_job_status_other', models.CharField(blank=True, help_text='If Others, specify here', max_length=100)),
                ('current_job_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
