# Generated by Django 5.2.1 on 2025-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='travelagencycv',
            name='language',
        ),
        migrations.AlterField(
            model_name='travelagencycv',
            name='language_other',
            field=models.CharField(blank=True, help_text='If Other, specify additional languages here', max_length=255),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='cvs', to='clients.language'),
        ),
    ]
