# Generated by Django 5.2.1 on 2025-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_language_remove_travelagencycv_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagencycv',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief introduction about yourself'),
        ),
    ]
