# Generated by Django 5.2.1 on 2025-05-29 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_travelagencycv_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Bangladeshi', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('place_of_issue', models.CharField(max_length=100)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
