# Generated by Django 5.2.1 on 2025-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_passportinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagencycv',
            name='national_id',
            field=models.IntegerField(blank=True, help_text='National ID', null=True, unique=True),
        ),
    ]
