# Generated by Django 5.2.1 on 2025-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('hr', 'HR'), ('agent', 'Agent'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
